clustering/urls.py
from django.contrib import admin
from django.urls import path, include
from clustering import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('real-data', views.real_data, name='real_data'),
    path('uncleanup', views.uncleanup_data, name='uncleanup'),
    path('cleanup', views.cleanup_data, name='cleanup'),
    path('excel-report', views.excel_report, name='excel_report'),
    path('html-report', views.html_report, name='html_report'),
    path('kmedoid/', include('kmedoid.urls', namespace='kmedoid')),
    path('spectral/', include('spectral.urls', namespace='spectral')),
]

kmedoid/urls.py
from django.urls import path
from . import views

app_name = 'kmedoid'
urlpatterns = [
    path('refresh-cluster', views.refresh_cluster, name='kmedoid_refresh'),
    path('cluster-0', views.kmedoid_cluster0, name='cluster_0'),
    path('cluster-1', views.kmedoid_cluster1, name='cluster_1'),
    path('cluster-2', views.kmedoid_cluster2, name='cluster_2'),
    path('cluster-3', views.kmedoid_cluster3, name='cluster_3'),
    path('cluster-4', views.kmedoid_cluster4, name='cluster_4'),
    path('cluster-5', views.kmedoid_cluster5, name='cluster_5'),
    # path('cluster-6', views.kmedoid_cluster6, name='cluster_6'),
    path('reports', views.kmedoid_reports, name='reports'),
]

spectral/urls.py
from django.urls import path
from . import views

app_name = 'spectral'
urlpatterns = [
    path('refresh-cluster', views.refresh_cluster, name='spectral_refresh'),
    path('cluster-0', views.spectral_cluster0, name='cluster_0'),
    path('cluster-1', views.spectral_cluster1, name='cluster_1'),
    path('cluster-2', views.spectral_cluster2, name='cluster_2'),
    path('cluster-3', views.spectral_cluster3, name='cluster_3'),
    path('cluster-4', views.spectral_cluster4, name='cluster_4'),
    path('cluster-5', views.spectral_cluster5, name='cluster_5'),
    path('reports', views.spectral_reports, name='reports'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clustering | {{ title_page }}</title>
    <!-- ICON -->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'/>

    <!-- STYLE -->
    <link rel="stylesheet" href="{% static 'css/css_grid.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    <!-- TOP NAVBAR -->
    <nav class="navbar">
        <div class="container-fluid">
            <div class="banner__wrapper">
                <a href="{% url 'real_data' %}" class="title__banner">Clustering</a>
            </div>
            <div class="navbar__wrapper">
                <ul class="navbar__list">
                    <li class="navbar__item">
                        <a href="{% url 'index' %}">Upload File</a>
                    </li>
                    {% if upload_file %}
                        <li class="navbar__item">
                            <a href="{% url 'real_data' %}">Data from Health Departement</a>
                        </li>
                        <li class="navbar__item">
                            <a href="{% url 'uncleanup' %}">Pre-Cleaned Data</a>
                        </li>
                        <li class="navbar__item">
                            <a href="{% url 'cleanup' %}">Cleaned Data</a>
                        </li>
                        <li class="navbar__item navbar__dropdown">
                            <a href="">
                                <span>Cluster Reports</span>
                                <i class='dropdown__icon bx bx-chevron-down'></i>
                            </a>
                        </li>

                        {% if cluster_view %}
                        <li class="navbar__item navbar__dropdown">
                            <a href="">
                                <span>Spectral Clustering</span>
                                <i class='dropdown__icon bx bx-chevron-down'></i>
                            </a>
                        </li>
                        <li class="navbar__item navbar__dropdown">
                            <a href="">
                                <span>Kmedoid Clustering</span>
                                <i class='dropdown__icon bx bx-chevron-down'></i>
                            </a>
                        </li>
                        {% endif %}
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <!-- SIDE NAVBAR -->
    <div class="sidenav__wrapper active" id="sidenav-wrapper" first="true">
        <nav class="sidenav">
            <div class="container-fluid">
                <div class="banner__wrapper">
                    <a href="" class="title__banner">Clustering</a>
                </div>
            </div>
        </nav>
        <div class="container-fluid">
            <ul class="sidenav__list">
                
                <!-- CLUSTER REPORTS -->
                <li class="sidenav__item sidenav__dropdown reports__dropdown">
                    <a href="">
                        <span>Cluster Reports</span>
                    </a>
                    <ul class="sidenav__dropdown__list">
                        <li class="sidenav__dropdown__item">
                            <a href="" id="download-html">
                                <span>HTML Profiling</span>
                            </a>
                        </li>
                        <li class="sidenav__dropdown__item">
                            <a href="{% url 'excel_report' %}">
                                <span>EXCEL Report</span>
                            </a>
                        </li>
                    </ul>
                </li>

                {% if cluster_view %}
                <!-- SPECTRAL CLUSTERING -->
                <li class="sidenav__item sidenav__dropdown spectral__dropdown  {{ spectral_active }}">
                    <a href="">
                        <span>Spectral Clustering Data</span>
                    </a>
                    <ul class="sidenav__dropdown__list">
                        <li class="sidenav__dropdown__item">
                            <a href="{% url 'spectral:cluster_0' %}">
                                <span>Data Cluster 0</span>
                            </a>
                        </li>
                        <li class="sidenav__dropdown__item">
                            <a href="{% url 'spectral:cluster_1' %}">
                                <span>Data Cluster 1</span>
                            </a>
                        </li>
                        <li class="sidenav__dropdown__item">
                            <a href="{% url 'spectral:cluster_2' %}">
                                <span>Data Cluster 2</span>
                            </a>
                        </li>
                        <li class="sidenav__dropdown__item">
                            <a href="{% url 'spectral:cluster_3' %}">
                                <span>Data Cluster 3</span>
                            </a>
                        </li>
                        <li class="sidenav__dropdown__item">
                            <a href="{% url 'spectral:cluster_4' %}">
                                <span>Data Cluster 4</span>
                            </a>
                        </li>
                        <li class="sidenav__dropdown__item">
                            <a href="{% url 'spectral:cluster_5' %}">
                                <span>Data Cluster 5</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="sidenav__item sidenav__dropdown spectral__dropdown {{ spectral_active }}">
                    <a href="">
                        <span>Spectral Clustering Report</span>
                    </a>
                    <ul class="sidenav__dropdown__list">
                        <li class="sidenav__dropdown__item">
                            <a href="{% url 'spectral:reports' %}?cluster=0">
                                <span>Report Cluster 0</span>
                            </a>
                        </li>
                        <li class="sidenav__dropdown__item">
                            <a href="{% url 'spectral:reports' %}?cluster=1">
                                <span>Report Cluster 1</span>
                            </a>
                        </li>
                        <li class="sidenav__dropdown__item">
                            <a href="{% url 'spectral:reports' %}?cluster=2">
                                <span>Report Cluster 2</span>
                            </a>
                        </li>
                        <li class="sidenav__dropdown__item">
                            <a href="{% url 'spectral:reports' %}?cluster=3">
                                <span>Report Cluster 3</span>
                            </a>
                        </li>
                        <li class="sidenav__dropdown__item">
                            <a href="{% url 'spectral:reports' %}?cluster=4">
                                <span>Report Cluster 4</span>
                            </a>
                        </li>
                        <li class="sidenav__dropdown__item">
                            <a href="{% url 'spectral:reports' %}?cluster=5">
                                <span>Report Cluster 5</span>
                            </a>
                        </li>
                    </ul>
                </li>

                <!-- KMEDOID CLUSTERING -->
                <li class="sidenav__item sidenav__dropdown kmedoid__dropdown {{ kmedoid_active }}">
                    <a href="">
                        <span>Kmedoid Clustering Data</span>
                    </a>
                    <ul class="sidenav__dropdown__list">
                        <li class="sidenav__dropdown__item">
                            <a href="{% url 'kmedoid:cluster_0' %}">
                                <span>Data Cluster 0</span>
                            </a>
                        </li>
                        <li class="sidenav__dropdown__item">
                            <a href="{% url 'kmedoid:cluster_1' %}">
                                <span>Data Cluster 1</span>
                            </a>
                        </li>
                        <li class="sidenav__dropdown__item">
                            <a href="{% url 'kmedoid:cluster_2' %}">
                                <span>Data Cluster 2</span>
                            </a>
                        </li>
                        <li class="sidenav__dropdown__item">
                            <a href="{% url 'kmedoid:cluster_3' %}">
                                <span>Data Cluster 3</span>
                            </a>
                        </li>
                        <li class="sidenav__dropdown__item">
                            <a href="{% url 'kmedoid:cluster_4' %}">
                                <span>Data Cluster 4</span>
                            </a>
                        </li>
                        <li class="sidenav__dropdown__item">
                            <a href="{% url 'kmedoid:cluster_5' %}">
                                <span>Data Cluster 5</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="sidenav__item sidenav__dropdown kmedoid__dropdown {{ kmedoid_active }}">
                    <a href="">
                        <span>Kmedoid Clustering Report</span>
                    </a>
                    <ul class="sidenav__dropdown__list">
                        <li class="sidenav__dropdown__item">
                            <a href="{% url 'kmedoid:reports' %}?cluster=0">
                                <span>Report Cluster 0</span>
                            </a>
                        </li>
                        <li class="sidenav__dropdown__item">
                            <a href="{% url 'kmedoid:reports' %}?cluster=1">
                                <span>Report Cluster 1</span>
                            </a>
                        </li>
                        <li class="sidenav__dropdown__item">
                            <a href="{% url 'kmedoid:reports' %}?cluster=2">
                                <span>Report Cluster 2</span>
                            </a>
                        </li>
                        <li class="sidenav__dropdown__item">
                            <a href="{% url 'kmedoid:reports' %}?cluster=3">
                                <span>Report Cluster 3</span>
                            </a>
                        </li>
                        <li class="sidenav__dropdown__item">
                            <a href="{% url 'kmedoid:reports' %}?cluster=4">
                                <span>Report Cluster 4</span>
                            </a>
                        </li>
                        <li class="sidenav__dropdown__item">
                            <a href="{% url 'kmedoid:reports' %}?cluster=5">
                                <span>Report Cluster 5</span>
                            </a>
                        </li>
                    </ul>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>


    {% block content %}
    {% endblock %}

    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/download_file.js' %}"></script>
    
    {% block javascript %}
    <script src="{% static 'js/input_file.js' %}"></script>
    {% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- MAIN CONTENT -->
<div class="page">
    <div class="container-fluid">
        <div class="content__wrapper">
            <div class="header__wrapper">
                <div class="refresh__toggler__wrapper">

                    {% if refresh_button_cluster_kmedoid %}
                    <a href="{% url 'kmedoid:kmedoid_refresh' %}?cluster={{ data_query_param }}" class="refresh__toggler" type="button">
                        Refresh
                        <i class='bx bx-refresh'></i>
                    </a>
                    {% endif %}

                    {% if refresh_button_cluster_spectral %}
                    <a href="{% url 'spectral:spectral_refresh' %}?cluster={{ data_query_param }}" class="refresh__toggler" type="button">
                        Refresh
                        <i class='bx bx-refresh'></i>
                    </a>
                    {% endif %}
                    
                    {% if refresh_button == False %}
                    <a href="{% url 'cleanup' %}?refresh_data=0" class="refresh__toggler" type="button">
                        Data Enters Machine Learning
                        <i class='bx bx-refresh'></i>
                    </a>
                    {% endif %}

                    {% if refresh_button %}
                    <a href="{% url 'cleanup' %}?refresh_data=1" class="refresh__toggler" type="button">
                        Refresh
                        <i class='bx bx-refresh'></i>
                    </a>
                    {% endif %}

                </div>
                <h2 class="title__page">{{ title_page }}</h2>
            </div>
            <div class="table__wrapper">
                <table class="table">
                    <thead>
                        <tr>
                            {% for title in title_data %}
                                <th class="text__center">{{ title }}</th>
                            {% endfor %}
                        </tr>
                    </thead>
                    <tbody>
                        {% for data in content_data %}
                        <tr>
                            {% for k, v in data.items %}
                                {% if k != 'index' %}
                                    <td class="text__center">{{ v }}</td>
                                {% endif %}
                            {% endfor %}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- LOADING -->
<div id="loading-wrapper" class="loading__wrapper">
    <div class="spinner__icon"></div>
    <p class="spinner__text">Generating Report</p>
</div>
{% endblock %}

templates/upload_file.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- MAIN CONTENT -->
<div class="page">
    <div class="container-fluid">
        <div class="upload__file__wrapper">
            <div id="drop-area">
                <p class="info__input__file">Drag and drop file here or</p>
                <label class="label__file" for="inputFile">Browse</label>
                <input type="file" id="inputFile"/>
            </div>
            <div id="displayFile"></div>
            <a href="{% url 'real_data' %}?upload_file=True" class="submit__file">SUBMIT</a>
        </div>
    </div>
</div>
{% endblock %}